### ISSUE TITLE
登录用户代码报错

### ISSUE THREAD

**Issue by halyon14** [Wangs-official/163Music2Tag#2]
我是会员，尝试登录报错如下

`Traceback (most recent call last):
  File "install.py", line 143, in <module>
    print('\n[!]出现错误!状态码：' + login_back.status_code + '\n返回内容：' + login_back.text + '\n 五秒后退出')
TypeError: can only concatenate str (not "int") to str`

配置 win10 , python3.8.9

**Comment by Wangs-official** [comment]
已修复，本人API被vercel制裁了所以用不了😂
运行一下`git pull origin`然后再运行`python3 install.py`就可以了
